Update ACME challenge link
urda/django-letsencrypt pull request #64
Opened 2018-03-06 19:14 UTC by paolodina

Closes #63

2018-03-06 19:17 UTC, urda commented
First of all big THANK YOU to you, @paolodina !

I've got a big week at work, but on the surface I don't see any issues with this. I'll make some time later this week to sit down and get this worked on 😄

2018-03-06 19:35 UTC, urda requested changes
Hey can you make these changes and re-base your commit please?

2018-03-06 19:35 UTC, urda commented on README.rst
> +`ACME challenge <https://tools.ietf.org/html/draft-ietf-acme-acme/>`_ objects you may
I would prefer if we linked to this URL that is listed at the old endpoint:

```
https://github.com/ietf-wg-acme/acme/
```

As it is quoted from:

```
NOTE: This Repository is Deprecated

This repository is not active and does not accurately reflect what Let's Encrypt currently implements. It's retained only for history.

All new work happens here: https://github.com/ietf-wg-acme/acme/ 
```

2018-03-06 19:36 UTC, urda commented on README.rst
> +`ACME challenge <https://tools.ietf.org/html/draft-ietf-acme-acme/>`_ objects you may
You will also need to rebase on to the `develop` branch for me.

2018-03-08 09:33 UTC, urda commented
Closing in favor of #65 , please be sure next time to update the same branch in the PR when you rebase or update after a review. I just happened to notice your proper commit in your `develop` branch before I went and cut my own commit.

2018-03-08 09:33 UTC, closed without merging

2018-03-08 09:40 UTC, paolodina commented
@urda I didn't mean to cause that trouble. Apologies.

2018-03-08 09:52 UTC, urda commented
@paolodina No worries! I wanted to make sure your work got in! Contributions are ALWAYS welcome for review!

I pulled your commit, and I'm working on adding it to `develop`. 😄